name: zxing_scanner
description: A Barcode scanner Widget that can be embedded inside flutter. It uses zxing-dart for all platforms.
version: 1.0.0
repository: https://github.com/shirne/zxing_scanner

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.2
  zxing_lib: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
