name: zxing_scanner
description: A Barcode scanner Widget that can be embedded inside flutter. It uses zxing-dart for all platforms.
version: 0.1.2
repository: https://github.com/shirne/zxing_scanner

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.0+4
  zxing_lib: ^0.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
